src/App.web.js, src/screens/List.js, src/screens/List.web.js
testing:
* App im browser öffnen
* **öffnet sich die Detailseite?** (immer gleicher Inhalt)
=> Detailscreen web

package.json, src/screens/List.js, yarn.lock
Type: Meistertask
Description:
* Abstand der liste nach oben ist raus
* android scroll Fehler, dass nicht nach unten geschellt werden konnte ist raus
How to test:
* Native: Abstände und scrolling testen
=> fix margins

.flowconfig, package.json, yarn.lock
=> Upgrad packages

src/components/ListDetails/VotePannel.js
Type: Issue #37 
Description:
fix missing alert massage for web
How to test:
open web and click on a vote panel on detail screen
=> add alert for web and fix issue #37

README.md
Type: Meistertest
Description:
Dev video hinzugefügt
How to test:
read readme
=> Add developer Video as gif

yarn.lock
Type: none
Description:
packages updated
How to test:
does all works?
=> Package updates #2

.flowconfig, index.js, package.json, src/graphql/client.js, src/graphql/mutations/setInstructinosShown.js, src/graphql/queries/isInstructionShown.js, src/graphql/resolvers/index.js, src/screens/index.js, yarn.lock
Description:
How to test:
install yarn
=> add graphQL with persistant storage

.flowconfig, .gitignore, __tests__/App.js, index.js, package.json, src/screens/Instructions.js, src/screens/index.js, yarn.lock
Description:
How to test:
App Starten und schauen ob man die Einleitung sieht und auf den startscreen kommt und wieder zurück
=> Instructionscreen

package.json, yarn.lock
Description:
How to test:
nichts zu testen. nur das package hinzugefügt
=> Sprint#3/styled components

src/screens/VoteList/Header.js
Description:
How to test:
go to search and view keyboard return key
=> search: change keyboard return key to search

src/screens/VoteList/Header.js
Type: Meistertask
Description:
How to test:
Zur suche gehen und schauen ob der cursor nun nicht mehr grün ist
=> search: change curser color for android

src/screens/Search/index.js, src/screens/VoteList/Header.js
Type: Meistertask
Description:
1. such input auf iOS war am springen wenn man zur suche wechselte
2. androiod suchscreen war blau
How to test:
app starten und schauen
=> Sprint#3/ui fixes#1

index.js, src/screens/SideMenu/index.js
Description:
How to test:
check menu width on devices
=> fix width of menu to alwais 80%

index.js, src/screens/Detail/index.js
Description:
How to test:
detail screen backbutton checken
=> make detail screen back button white

.env, .env.android, .env.production, android/app/build.gradle, android/app/src/main/java/com/democracyclient/MainApplication.java, android/settings.gradle, dummy/voteLists.js, index.js, ios/democracyclient.xcodeproj/project.pbxproj, ios/democracyclient/Info.plist, package.json, src/components/Date.js, src/components/VoteListItem.js, src/graphql/client.js, src/graphql/queries/getProcedures.js, src/screens/Detail/Segments/Details.js, src/screens/Detail/index.js, src/screens/Instructions.js, src/screens/VoteList/List.js, src/screens/VoteList/index.js, yarn.lock
Description:
How to test:
yarn
app starten
=> Sprint#4/get data from server

ios/democracyclient.xcodeproj/project.pbxproj, ios/democracyclient/Info.plist
=> add ipad to device family

src/screens/VoteList/index.js
=> make tabbar-text smaler on ios >= 320 px

.env.production, ios/democracyclient.xcodeproj/project.pbxproj, ios/democracyclient/Info.plist, src/components/Date.js, src/graphql/queries/getProcedures.js, src/screens/Detail/Segments/Details.js, src/screens/Detail/index.js, src/screens/VoteList/List.js
Description:
How to test:
go to detailscreen
=> add procedureId to detailscreen

src/screens/Detail/Segments/Details.js
Type: Issue #87 
Description:
Textgröße auf detailscreen vergrößert
How to test:
zum detailscreen navigieren
=> increase font-size from 11 to 13 #87

android/app/build.gradle, index.js, ios/democracyclient/Info.plist, src/graphql/mutations/setCurrentScreen.js, src/graphql/queries/currentScreen.js, src/graphql/resolvers/index.js, src/screens/Instructions/index.js, src/screens/SideMenu/Navigation.js, src/screens/SideMenu/index.js, yarn.lock
Navigation vorbereitet um Seiten zu wechseln
App Starten
Burgermenü offnen,
rumklicken
=> prepare navigation functionality

src/screens/Detail/Segment.js, src/screens/Detail/Segments/Details.js, src/screens/Detail/Segments/Documents.js, src/screens/Detail/index.js
Type: Issue #93 #96 #97 
Description:
Layoutanpassungen durchgeführt
How to test:
Issues Gegenchecken
=> Sprint#5/detail screen layout fixes

src/graphql/client.js, src/screens/Detail/index.js, src/screens/VoteList/List.js
Type: improvement
Description:
Daten wurden bisher immer nur aus dem cache gelesen und nicht aktualisiert.
Nun werden die Daten erst aus dem cache gelesen und angezeigt, worauf eine abfrage des servers folgt um ggf. die Inhalte aktualisiert anzuzeigen.
How to test:
app starten
zu Detailscreen navigieren
daten betrachten
Aktualisierung abwarten/provozieren
zurück zur liste und wieder auf den detailscreen gehen
=> Sprint#5/refetch

package.json
=> repari versioning for macOS

src/screens/VoteList/Header.js, src/screens/VoteList/List.js
fix #95
Type: #95
Description:
Abstände waren zu gering
How to test:
=> increase header padding on ios list header

ios/democracyclient/Info.plist, package.json
=> version 0.0.9

.flowconfig, index.js, package.json, src/screens/SideMenu/Navigation.js, src/screens/SideMenu/index.js, src/screens/Support.js, src/screens/VoteList/List.js, src/screens/VoteList/index.js, src/screens/VoteList/topTabs.js, src/screens/index.js, src/screens/onNavigationEvent.js, yarn.lock
How to test:
`yarn`
test burger menu
=> tabwechsel auf ios optmieren + Navigation ermöglichen

ios/democracyclient.xcodeproj/xcshareddata/xcschemes/democracyclient-prod.xcscheme
share missing production scheme for travis
https://stackoverflow.com/questions/35198798/travis-ci-with-error-cannot-find-schemes
How to test:
approve and rebuild master on travis
=> schare democracyclient-prod scheme for travis

package.json
Travis Log is to long - added quiet mode
=> add -quiet mode

ios/democracyclient/Info.plist
**Type:** Issue #X | Meistertask | Extern
=> remove preversion

.travis.yml
**Type:** Issue #X | Meistertask | Extern
=> do not run travis pr job on merging to master

src/config/index.js, src/graphql/client.js, src/screens/Support.js
[![Build Status](https://travis-ci.org/demokratie-live/democracy-client.svg?branch=master)](https://travis-ci.org/demokratie-live/democracy-client)
es wurden nur die env aus der .env Datei verwendet, jetzt werden bevorzugt die cli env's verwendet
=> use cli environment variables first

.travis.yml, src/graphql/client.js
Url für android wieder verfügbar gemacht
=> fix android graphql server url

src/screens/Search/Header.android.js
**Type:** Issue #143
X bei der suche setzt die Ergebnisse nun wieder zurück
suche starten und X drücken
=> [Android] reset search results on click X

src/screens/Search/Header.android.js, src/screens/Search/Header.ios.js, src/screens/Search/index.js
Der Suchstatus ist unschön gesprungen
bei der suche schnell tippen
=> fix search status issue

.travis.yml
=> fixed android deploy

.travis.yml
Fix for #142
Check if Discord Hook announces new Play/AppStore Versions after merge
=> Sprint#6/encrypted webhook

android/app/build.gradle, android/app/src/main/java/com/democracyclient/MainApplication.java, android/settings.gradle, index.js, ios/democracyclient.xcodeproj/project.pbxproj, ios/democracyclient/Info.plist, package.json, src/components/ActivityIndex.js, src/components/VoteListItem.js, src/config/index.js, src/graphql/client.js, src/graphql/mutations/increaseActivity.js, src/graphql/mutations/signUp.js, src/graphql/queries/activityIndex.js, src/graphql/queries/getProcedure.js, src/graphql/queries/getProcedures.js, src/graphql/queries/me.js, src/graphql/queries/searchProcedures.js, src/screens/Detail/index.js, src/screens/VoteList/List.js, src/screens/VoteList/index.js, yarn.lock
Direkte activity-aktion ermöglicht
=> ActivityIndex

src/graphql/client.js
soll nur eine neue version mit dem key erstellen
=> push create new version

CHANGELOG.md, ios/democracyclient-tvOS/Info.plist, ios/democracyclient-tvOSTests/Info.plist, ios/democracyclient/Info.plist, ios/democracyclientTests/Info.plist, ios/fastlane/Fastfile, ios/fastlane/README.md, package.json, src/screens/Instructions/Slide.js, src/screens/Instructions/index.js
=> Sprint#7/tutorial

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/screens/Detail/Segment.js, src/screens/Detail/Segments/VoteResults.js, src/screens/Detail/index.js
**Issue:** #165
#165
öffne unter Abstimmungen folgende Abstimmung
**Checklist:**
https://github.com/demokratie-live/democracy-development/pull/15
=> Fix votePie errors 

CHANGELOG.md, ios/democracyclient/Info.plist, package.json
=> remove emoji from changelog

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/screens/Detail/index.js
**Issue:** fixes #196
Fixes Reloading Details Blank out Bug on Android
Reload Details Screen
**Checklist:**
=> fixed reloading bug of detailscreen android

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/screens/Support.js
**Issue:** #193
Support Screen Links
Click on Buttons in Android Android
**Checklist:**
=> fixed support contacts

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/components/ActivityIndex.js, src/components/VoteListItem.js, src/graphql/client.js, src/graphql/fragments/ProcedureActivityIndex.js, src/graphql/queries/getProcedure.js, src/graphql/queries/getProcedures.js, src/graphql/queries/notifiedProcedures.js, src/screens/Detail/Segments/VoteResults.js, src/screens/Detail/Voting.js, src/screens/Detail/index.js, src/screens/Notifications/index.js, src/screens/VoteList/List.js, src/screens/VoteVarification/BallotBox.js
https://github.com/demokratie-live/democracy-development/pull/39
**Checklist:**
=> fix refetch data from server

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/components/VoteListItem.js, src/screens/Detail/index.js
**Issue:** #XXX
**Checklist:**
=> fix android crash by checking tags

README.md
**Issue:** fixes #225
New Sprint4 Video as Gif + YT Link
read readme
- no version required
- no changelog required
- no PR on development required
**Checklist:**
=> New Sprint4 Video as Gif + YT Link

ios/democracyclient-tvOS/Info.plist, ios/democracyclient-tvOSTests/Info.plist, ios/democracyclient.xcodeproj/project.pbxproj, ios/democracyclient/Info.plist, ios/democracyclientTests/Info.plist, ios/fastlane/README.md
lets try it with travis 😎
https://github.com/demokratie-live/democracy-development/pull/79
**Checklist:**
=> sprint#11/fix-apple-upload

android/fastlane/Fastfile
Corrected Metadata paths (WHY FASTLANE WHY?)
Deploy
**Checklist:**
=> [Hotfix] metadata paths

ios/fastlane/Fastfile
**Issue:** #XXX
changing length was too long
https://github.com/demokratie-live/democracy-development/pull/80
-
**Checklist:**
=> sprint#11/fix testflight changelog

CHANGELOG.md, index.js, ios/democracyclient/Info.plist, package.json, src/components/VoteButton.js, src/screens/Detail/Voting.js, src/screens/Detail/index.js, src/screens/Notifications/InAppNotification.js, src/screens/VoteVarification/BallotBox.js, src/screens/index.js
Disabled PushNotifications
Update Server and send testPush -> should not reach client
**Checklist:**
=> Sprint#11/disable push notifications

CHANGELOG.md, src/screens/Detail/Voting.js
**Issue:** #302
change vote button labels after voting
do vote and check labels
**Checklist:**
=> sprint#11/vote-button-labels#2

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/components/VoteButton.js, src/screens/Detail/Voting.js, src/screens/Detail/index.js, src/screens/Notifications/InAppNotification.js, src/screens/VoteVarification/BallotBox.js, src/screens/index.js
**Issue:** #301
https://github.com/demokratie-live/democracy-client/issues/301
check bell position
**Checklist:**
=> sprint#11/bell-position

CHANGELOG.md, src/components/Document.js, src/screens/Detail/Segment.js, src/screens/Detail/Segments/Details.js, src/screens/Detail/Voting.js, src/screens/Detail/index.js
**Issue:** fixes #260 & fixes #223 
* Details
* Increased all font sizes by 1pt [#260](https://github.com/demokratie-live/democracy-client/issues/260)
* Increased contrast of "Inhalt" by 5pt [#223](https://github.com/demokratie-live/democracy-client/issues/223)
Check Details Page - readability vs style
**Checklist:**
=> Sprint#12/font size contrast

.travis.yml, CHANGELOG.md, Gemfile, ios/democracyclient/Info.plist, package.json, src/graphql/client.js
* [HOTFIX] increase offline cache to prevent lost vote data [#322](https://github.com/demokratie-live/democracy-client/issues/322)
=> Alpha/client 0.7.8 hotfix

.travis.yml, Gemfile
**Issue:** none
travis ran in timeout on fastlane update_fastlane
try gem update fastlane
check travis
https://github.com/demokratie-live/democracy-development/pull/110
**Checklist:**
=> change fastlane selfupdate method

.travis.yml, CHANGELOG.md, Gemfile, src/graphql/client.js
**Issue:** #322
hotfix to prevent lost local vote data
vote on some procedures,
try to increase cache by open nearly all procedures
https://github.com/demokratie-live/democracy-development/pull/114
**Checklist:**
=> sprint#15/vote-data-lost-hotfix

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/components/ActivityIndex.js, src/graphql/queries/notifiedProcedures.js, src/graphql/queries/searchProcedures.js, src/screens/Detail/Segments/VoteResults/PieChart.js, src/screens/Search/index.js
**Issue:** #312 
https://github.com/demokratie-live/democracy-client/issues/312
search -> do increase activity index -> check listView in search
https://github.com/demokratie-live/democracy-development/pull/107
**Checklist:**
=> Sprint#15/search activity index

.travis.yml, CHANGELOG.md, Gemfile, src/graphql/queries/getProcedure.js, src/screens/Detail/Segments/Details.js, src/screens/Detail/index.js
**Issue:** #328 
https://github.com/demokratie-live/democracy-development/pull/108
check vote ready unvoted and voted by government procedure
vote this procedure and check if it changes correctly
https://github.com/demokratie-live/democracy-development/pull/108
**Checklist:**
=> Sprint#15/hide current status

.travis.yml, CHANGELOG.md, Gemfile, src/components/ListSectionHeader.js
**Issue:** #308 
https://github.com/demokratie-live/democracy-client/issues/308
check list view (scroll to "Vergangen")
https://github.com/demokratie-live/democracy-development/pull/109
**Checklist:**
=> Sprint#15/voted segment header

.travis.yml, CHANGELOG.md, Gemfile, index.js, src/graphql/client.js
**Issue:** #281
tokenabfrage aus dem app start ausgelagert
app mit, ohne und langsamer zugriff zu einem server testen (app neu installieren etc) dieses PR sollte etwas intensiver getestet werden.
https://github.com/demokratie-live/democracy-development/pull/111
**Checklist:**
=> improve app start performance

.travis.yml, CHANGELOG.md, Gemfile, src/screens/Detail/Segments/VoteResults/PieChart.js
**Issue:** #310 
https://github.com/demokratie-live/democracy-client/issues/310#issuecomment-391386022
check pie chart labels
https://github.com/demokratie-live/democracy-development/pull/112
**Checklist:**
=> Sprint#15/vote result labels

CHANGELOG.md, android/build.gradle, index.js
**Issue:** #354
https://github.com/demokratie-live/democracy-client/issues/354
swipe from left to right in detailscreen
https://github.com/demokratie-live/democracy-development/pull/120
**Checklist:**
=> sprint#16/menu-opening

CHANGELOG.md, src/components/ActivityIndex.js, src/components/Date.js, src/components/VoteListItem.js, src/screens/Search/index.js, src/screens/VoteList/List.js
**Issue:** #358
fix #358
1-2 imports durchlaufen lassen
https://github.com/demokratie-live/democracy-development/pull/121
**Checklist:**
=> sprint#16/bt-agenda

README.md
remove web client version from readme
=> sprint#16/readme

CHANGELOG.md, src/screens/Detail/Voting.js, src/screens/Detail/index.js
**Issue:** #378
Über was wird abgestimmt? Beschlussempfehlung oder den Antrag/Gesetz an sich.
Die Überschrift des segment headers soll dies klarstellen
Prozedur in Abstimmung öffnen
https://github.com/demokratie-live/democracy-development/pull/129
**Checklist:**
=> sprint#18/Vote Segment Header

CHANGELOG.md, src/screens/VoteList/List.js
**Issue:** #368
Zeige in der liste an ob mehr Daten geladen werden
scroll in a list to the bottom
https://github.com/demokratie-live/democracy-development/pull/130
**Checklist:**
=> sprint#18/Load More Indicator

CHANGELOG.md, android/build.gradle, src/graphql/queries/getProcedure.js, src/screens/Detail/Segments/History.js, src/screens/Detail/index.js
**Issue:** none
Hide vote result in history if not voted
check history on voted procedures 
https://github.com/demokratie-live/democracy-development/pull/134
**Checklist:**
=> Sprint#18/current status history#2

CHANGELOG.md, src/components/ListSectionHeader.js
**Issue:** none
reset segment header
check on list & Benachrichtigungen
https://github.com/demokratie-live/democracy-development/pull/140
**Checklist:**
=> sprint#19/segment-header-style

CHANGELOG.md, src/screens/Detail/Segments/VoteResults.js
**Issue:** none
Change Government PieChart Colors
check government pie chart colors
https://github.com/demokratie-live/democracy-development/pull/141
**Checklist:**
=> sprint#19/piechart color

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/suggestion.md, .github/PULL_REQUEST_TEMPLATE.md
Fixed encoding and default issue
None
None
=> sprint#22/issue_pr_templates#2

package.json, yarn.lock
Remove insecure depencency
- fixes #490
=> sprint#23/vulnerability_fix

CHANGELOG.md, src/screens/Detail/Segments/History.js
=> sprint#31/Meilensteinkarte

src/screens/Detail/index.js
=> sprint#31/notifications

CHANGELOG.md, src/screens/Search/Header.android.js, src/screens/Search/Header.ios.js, src/screens/Search/index.js
fix show no results on klick keyboard search button
- fixes #XXX
- relates #XXX
=> sprint#36/serach-fixes

CHANGELOG.md, src/hocs/PushNotifications.js
Fixes Push's for Android
- resolves https://github.com/demokratie-live/democracy-client/issues/373
- fixes https://github.com/demokratie-live/democracy-client/issues/454
=> sprint#36/fix_push_android

CHANGELOG.md, src/screens/VoteList/List.js
improve filter performance for not-/voted
- fixes #XXX
- relates #XXX
=> sprint#36/filter-performance

android/Gemfile.lock
Bump Version of rubyzip to 1.2.2
=> sprint#36/security_vulnerability_rubyzip

CHANGELOG.md, ios/democracyclient/Info.plist, package.json, src/components/Checkbox.js, src/screens/VoteList/Filter/index.js
Changed Filter Checkmark Colors for better understanding
=> Sprint#38/filter colors

CHANGELOG.md, src/graphql/queries/getStatistic.js, src/graphql/queries/getVotedProcedures.js, src/screens/SideMenu/Navigation.js, src/screens/SideMenu/index.js, src/screens/Statistic.js, src/screens/index.js, yarn.lock
Statistic in Burgermenu + Head
=> Sprint#36/statistic

android/fastlane/Appfile, android/fastlane/Fastfile
Production deploy on internal lane for now
=> Sprint#35/deployment

CHANGELOG.md, package.json, src/screens/Detail/index.js, src/services/shareLink.js, yarn.lock
=> Sprint#36/share

CHANGELOG.md, src/screens/Detail/Segments/VoteResults/PieChart.js, src/screens/Statistic.js, yarn.lock
=> sprint#39/hotfix-svg-charts

CHANGELOG.md, src/screens/Donate/index.js, src/screens/SmsVerification/Code.js, src/screens/SmsVerification/Success.js
=> sprint#39/fix-donate-crash

CHANGELOG.md, src/screens/Detail/Segments/VoteResults/PieChart.js
=> sprint#39/fix-android-community-vote-numbers

CHANGELOG.md, src/screens/Support.js
=> sprint#39/support_typo

CHANGELOG.md, src/components/ActivityIndex.js, src/components/Date.js, src/screens/Detail/index.js, yarn.lock
Abstimmung text zu Restzeit auf Detailseite hinzugefügt
=> Sprint#42/rest time

CHANGELOG.md, package.json, src/graphql/client.js, src/graphql/queries/donationStatus.js, src/screens/Donate/content.js, src/screens/Donate/index.js, src/screens/SideMenu/index.js, yarn.lock
resolves https://github.com/demokratie-live/democracy-client/issues/587
=> sprint#42/donation-api

CHANGELOG.md, src/screens/VoteList/Filter/index.js
[Filter] Rename "Aktivitäten" to "Eigene Aktivitäten"
=> sprint#43/eigene_aktivität

CHANGELOG.md, src/screens/Detail/Segments/VoteResults/BarChart.js, src/screens/Detail/Segments/VoteResults/PartyChart.js, src/screens/Detail/Segments/VoteResults/PieChart.js
[Details] Adjusted chart legend label colors for better readability
=> sprint#43/chart_legend_label_colors

CHANGELOG.md, src/screens/Detail/Segments/VoteResults.js, src/screens/Detail/index.js, yarn.lock
show government results without own vote for past procedures
=> sprint#43/show-past-voteResults

CHANGELOG.md, src/screens/Detail/Segments/VoteResults/PartyChart.js, src/screens/Detail/Segments/VoteResults/PieChart.js, src/screens/Statistic.js
[Charts] Unified all Chart Fonts
=> sprint#43/charts_unify_fonts

CHANGELOG.md, src/screens/Detail/Segments/VoteResults/BarChart.js, yarn.lock
=> sprint#43/barChart-pixel

CHANGELOG.md, src/screens/Detail/Segments/VoteResults.js
=> sprint#42/named-vote-info

CHANGELOG.md, src/screens/Donate/DonatedBox.js, src/screens/Donate/index.js
=> sprint#43/Donation-Bar-Gap

README.md
=> Sprint#45/readme gettingstarted

ios/democracyclient.xcodeproj/project.pbxproj
=> Sprint#19/2/react native update permissions

ios/democracyclient.xcodeproj/project.pbxproj
=> fix min lib ios target

src/screens/VoteList/List.js
=> sprint#50/new-list-past

README.md
Changed the readme to add maintainers images and resolve issue #466 
- fixes #466
=> 🛠 [Documentation] Changed ReadMe to reflect the Maintainers Images as per Github

src/screens/Imprint/content.js
Fix für #808.
Entfernt ungenutzte Kommentare, insb. Google Analytics Tracking.
=> Removed unnecessary comments and fixed #808

README.md
This will only be displayed once the docu-pr is merged!
> https://github.com/demokratie-live/democracy-docu/pull/1
=> updated Readme, included Systemmap

package.json, packages/mobile-app/android/app/build.gradle, packages/mobile-app/android/app/src/main/AndroidManifest.xml
=> remove duplicate app icon

.github/workflows/pull-request.yml
=> add pull request check

packages/mobile-app/android/fastlane/Fastfile
=> do not double build

packages/mobile-app/android/fastlane/Fastfile
=> build for browserstack

.github/workflows/lint.yml
=> save apk & abb as artifact

packages/mobile-app/e2e/tests/Verification.test.ts, packages/mobile-app/package.json
=> add test verification scenario #4 restart app before code input

packages/mobile-app/src/screens/Bundestag/List/NoConferenceWeekData.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/Voting/components/NoConstituency.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/Voting/components/PartyChart.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/CommunityVoteResults.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/GovernmentVoteResults/Deputy.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/GovernmentVoteResults/index.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/History.tsx, packages/mobile-app/src/screens/Sidebar/Donate/Entry.tsx, packages/mobile-app/src/screens/WahlOMeter/MemberProfil/Chart.tsx, packages/mobile-app/src/screens/WahlOMeter/MemberProfil/index.tsx, packages/mobile-app/src/screens/WahlOMeter/Wahlkreis/index.tsx, packages/mobile-app/src/screens/modals/Constituency/index.tsx, packages/mobile-app/src/screens/modals/Introduction/PushInstructions/index.tsx, packages/mobile-app/src/screens/modals/NotificationInstruction/index.tsx, packages/mobile-app/src/screens/modals/Verification/Donate.tsx, packages/mobile-app/src/styles/theme.ts, packages/mobile-ui/src/components/Introduction/Header.tsx, packages/mobile-ui/src/components/Introduction/Slide.tsx
=> fix more colors

.github/workflows/lint.yml
=> do only test on pr not on normal push

packages/mobile-app/src/lib/Apollo/Version.ts, packages/mobile-app/src/lib/Apollo/index.tsx
=> add version to api header

packages/mobile-app/src/screens/modals/NotificationInstruction/index.tsx
=> fix push box padding on bell

packages/mobile-app/android/build.gradle
=> update api level from 28 to 29

package.json, packages/mobile-app/package.json
=> upgrade version

.github/workflows/lint.yml, package.json, packages/mobile-app/package.json
=> change android test action

.github/workflows/lint.yml
=> use node 14 instead of 12

package.json, yarn.lock
=> remove docz

packages/mobile-app/src/routes/Sidebar/Bundestag/index.tsx
=> change search screen title to „Suche“

.github/workflows/lint.yml, packages/mobile-app/e2e/helpers/verification.ts, packages/mobile-app/e2e/tests/Verification.test.ts, packages/mobile-app/package.json
=> update xcode version

packages/mobile-app/src/components/misc/Pagination.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/CommunityVoteResults.tsx
=> adjust carousel spaces

packages/mobile-app/package.json, packages/mobile-app/src/screens/Bundestag/Procedure/Voting/index.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/GovernmentVoteResults/PartyChart.tsx, packages/mobile-app/src/screens/WahlOMeter/Fraktionen/WomPartyChart.tsx, yarn.lock
=> improve BarCharts

packages/mobile-app/package.json, packages/mobile-app/src/screens/WahlOMeter/Wahlkreis/index.tsx, yarn.lock
=> replace bar Chart

packages/mobile-app/src/screens/Bundestag/Procedure/Voting/index.tsx
=> center vote screen subtitle

packages/mobile-app/e2e/tests/Verification.test.ts, packages/mobile-app/ios/Podfile.lock, packages/mobile-app/package.json, packages/mobile-app/src/screens/Bundestag/Procedure/components/CommunityVoteResults.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/CountryMap/index.tsx, yarn.lock
=> fix orientation change crash

packages/mobile-app/src/screens/WahlOMeter/Wahlkreis/index.tsx
=> fix wom constituency bar data

packages/mobile-app/src/screens/modals/Faq/data.ts
=> fix syntax in faq

packages/mobile-app/src/lib/rateApp.ts
=> auto select android bundle identifier for app rate

packages/mobile-app/src/__generated/apollo-helpers.ts, packages/mobile-app/src/routes/Sidebar/Bundestag/TabView.tsx, packages/mobile-app/src/routes/Sidebar/Bundestag/graphql/__generated__/ShowRecommendations.ts, packages/mobile-app/src/routes/Sidebar/Bundestag/graphql/showRecommendations.ts, packages/mobile-app/src/screens/Bundestag/DevPlaceholder.tsx, packages/mobile-app/src/screens/Bundestag/List/index.tsx, packages/mobile-app/src/screens/Bundestag/Procedure/components/DocumentItem.tsx, packages/mobile-app/src/screens/Bundestag/Recomended/graphql/__generated__/RecommendedProcedures.ts, packages/mobile-app/src/screens/Bundestag/Recomended/graphql/recommendedProcedures.ts, packages/mobile-app/src/screens/Bundestag/Recomended/index.tsx, packages/mobile-app/src/screens/Bundestag/Recomended/styled.ts
=> add recommended list

package.json, packages/mobile-app/package.json, packages/mobile-app/src/screens/Bundestag/Search/Header.tsx
=> fix android search bug

packages/mobile-app/src/screens/modals/Faq/data.ts
1. 1.4 FAQ geprüft
2. um alles bereinigt, was nach der BTW nicht mehr nötig ist
3. 'Wo finde ich die Gesetze der vergangenen Legislaturperiode 19?' hinzugefügt
=> Update FAQ to 1.5

README.md, docs/ARCHITECTURE.md, docs/TESTING.md, docs/deployment/ANDROID.md, docs/deployment/IOS.md
This pull request includes comprehensive documentation updates for the DEMOCRACY client application, covering the README, architecture, testing, and deployment processes. Below are the most important changes:
* **README.md**: Added detailed information about the DEMOCRACY client, including features, technology stack, getting started instructions, development guidelines, testing, deployment, project structure, architecture, license, and contact information.
* **Architecture Documentation**: Introduced a new `ARCHITECTURE.md` file that outlines the application's architecture, including the technology stack, project structure, key architecture concepts, navigation, data flow, component architecture, state management, authentication flow, app variants, testing strategy, and performance …
=> feat: add testing and deployment documentation for iOS and Android

src/app/(sidebar)/[legislaturePeriod]/Deputies.tsx, src/components/Sidebar/Parlaments/Parlament.tsx, src/components/Sidebar/Parlaments/Parlaments.tsx, src/screens/Verification/Donate.tsx
This pull request includes various changes to improve the functionality of the Deputies and Sidebar components, as well as some styling updates across multiple files.
Improvements to Deputies and Sidebar components:
* `src/app/(sidebar)/[legislaturePeriod]/Deputies.tsx`: Added `key` prop to `AbgeordneteScreen` to ensure it re-renders when `legislaturePeriod` changes. ([src/app/(sidebar)/[legislaturePeriod]/Deputies.tsxR9](diffhunk://#diff-186b9c2e3446ca5201f125ae63f765883e0e2e9d1b4a8743d7efb5ae5bfed94bR9))
* [`src/components/Sidebar/Parlaments/Parlament.tsx`](diffhunk://#diff-d24602d0b61d16ef294bd95efb6e4369cbfaafd1e8f33f8b98b25daf3d1d3a68L4-R4): Added `useSegments` import and integrated it to determine the current tap for focus checks. …
=> Man an ruck/fix layout
